### ISSUE TITLE
欄位順序

### ISSUE THREAD

**Issue by azole** [bo-yuan026/node-workshop#5]
https://github.com/bo-yuan026/node-workshop/blob/e97e859afb2df9327f0152844fe66981388149fc/crawler/crawler-db2.js#L51

你的程式我有下載下來執行，發現會有 exception，檢查了一下，發現應該是這邊欄位的順序，跟你 insertData 的資料順序是不相符的，你可以測試看看 2330 這個股票代碼在你那邊是否能成功嗎？  也確認一下這邊欄位的順序是否符合你資料的順序喔。

**Comment by bo-yuan026** [comment]
好，我中午會再測試看看

**Comment by bo-yuan026** [comment]
老師晚安，我已經上傳改寫完成的版本，雖然可以成功傳進資料庫但是有些問題
想問一下 https://github.com/bo-yuan026/node-workshop/blob/60015ffdabb5db520fec25f853f1904adcf0f975/crawler/crawler-db2.js#L69
L69 的Promise物件是為了進stock內檢查有沒有一樣的股票代碼，再丟進 L79的 if 判斷，但我得到的變數都會等於我在 stock.txt 上面的數字，就算故意寫成1234 也是得到1234 所以沒辦法進到 if 裡面，是不是要把這個判斷搬到async function外面才可以呢?

**Comment by azole** [comment]
L69 這邊，是不是要有 await，這樣 queryStock 才能接回 resolve 後傳出來的值呢？

再來是「我得到的變數都會等於我在 stock.txt 上面的數字」-> 這行你是怎麼判斷的？ 你有 console.log(queryStock)，因為我好像沒有看到，所以想確定一下你是怎麼判斷你得到的變數都等於 stock.txt 裡的？

**Comment by bo-yuan026** [comment]
!!!! 剛剛寫出來了，跟大家一起開會的時候看姝璇解釋Promise的時候發現Promise要在async外面，當在async內呼叫並且await他回來之後才能得到想要的數值，不然會一直印出Promise{pending}

**Comment by azole** [comment]
哈哈，太棒了，看來你的收穫最大，程式除了幾個小地方外（我另外開 issue），沒什麼問題了，這個 issue 可以先關起來了。
